# -*- coding: utf-8 -*-
"""Code evaluation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QtUkBp_LOeu7I1eA7RYG_Zdod-VBwIcc

# Loading Dataset

https://github.com/CASTLE-Benchmark/CASTLE-Benchmark

The dataset contains C programs named in the pattern CASTLE-ID-variant.c, for example CASTLE-125-1.c, CASTLE-125-2.c, CASTLE-125-3.c, CASTLE-134-2.c,CASTLE-134-3.c. Each group of files shares the same vulnerability type but differs in implementation details.
"""

import os
import subprocess
from pathlib import Path

CASTLE_REPO = "https://github.com/CASTLE-Benchmark/CASTLE-Benchmark.git"
# Fix: Use a path relative to the current working directory in Colab
DATA_DIR = Path("/content") / "data" / "CASTLE-Benchmark"

def clone_if_needed():
    if DATA_DIR.exists():
        print("CASTLE already cloned at", DATA_DIR)
        return
    DATA_DIR.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "clone", CASTLE_REPO, str(DATA_DIR)], check=True)
    print("Cloned CASTLE to", DATA_DIR)

def list_cases():
    # CASTLE repo structure: each test is under e.g. tests/... (repo may change — inspect after cloning)
    # Here we do a simple walk to collect .c/.h files
    file_list = []
    for p in DATA_DIR.rglob("*.c"):
        file_list.append(str(p))
    for p in DATA_DIR.rglob("*.cpp"):
        file_list.append(str(p))
    print(f"Found {len(file_list)} source files")
    return file_list

if __name__ == "__main__":
    clone_if_needed()
    files = list_cases()
    # Optionally save listing
    out = DATA_DIR.parent / "file_listing.txt"
    out.write_text("\n".join(files))
    print("Wrote listing to", out)
